# Generated by Django 5.0.3 on 2025-04-14 16:51

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('users', '0003_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('place', models.CharField(max_length=200, verbose_name='место установки')),
                ('characteristic', models.TextField(blank=True, verbose_name='характеристика')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='users.category', verbose_name='категория')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='теги')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['slug'],
                'indexes': [models.Index(fields=['title', 'slug'], name='users_equip_title_93ac1b_idx')],
            },
        ),
    ]
