# Generated by Django 5.0.3 on 2025-04-14 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, verbose_name='описание ремонта')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='users.equipment', verbose_name='оборудование')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='сотрудник')),
            ],
            options={
                'verbose_name': 'Журнал ТО/ТР',
                'verbose_name_plural': 'Журнал ТО/ТР',
                'ordering': ['-time_create'],
            },
        ),
    ]
