# Generated by Django 5.0.3 on 2025-04-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='название')),
                ('schema_image', models.ImageField(blank=True, default=None, null=True, upload_to='shema/%Y/%m/%d/', verbose_name='Схемы')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'Схема',
                'verbose_name_plural': 'Схемы',
                'ordering': ['-time_create'],
            },
        ),
    ]
